# Generated by Django 3.2.5 on 2021-08-02 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('relationship', models.CharField(max_length=50)),
                ('number', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=300)),
                ('address', models.CharField(max_length=200)),
            ],
        ),
    ]
